### ISSUE TITLE
Make run for all world saves

### ISSUE THREAD

**Issue by xJon** [jamezrin/voxel2xaero#1]
Hi,
Is there any way you could make the script automatically run over all of the world saves in a modpack instance?
I could make your script run per world folder but it'd be more convenient if the script could do it on its end.

**Comment by jamezrin** [comment]
Good idea! I'll add this soon

**Comment by jamezrin** [comment]
By 39910728a3d6a53caa3ef90b1df35d7fa5eeeb85 this is the default behavior

**Comment by xJon** [comment]
Thank you :)
